### PR TITLE
Problem: We need to rename the project to fty-common-logging.

### PR DESCRIPTION
**Pull request by jana-rapava**
Solution: Do it; regen; remove the old files.

Signed-off-by: Jana Rapava <janarapava@eaton.com>

### CODE REVIEW

**Comment by michal42** [comment]
@bstepankova, if you ask me -- If it ain't broke, don't fix it. But if @aquette insists on the renaming, then let's rename it and fix up any fallout. If we also rename the github repository itself, then yes, Jenkins will probably need an update.

**Comment by michal42** [comment]
Now I re-read you question properly. I don't think that name1.git and name2 in project.xml should be a problem per se. But it's certainly something to watch out for.

**Comment by EldoreiJK** [comment]
Jenkins will find new repo based on jenkinsfile, and do it pretty quickly - verified with fty-licensing. OBS will indeed break, as it will have issues with installed libraries. But that's the life. It will be the same for fty-common split, you'll see :)

**Comment by bstepankova** [comment]
why don't we create new repository for common-logging and then remove fty-log once not needed?

**Comment by michal42** [comment]
We can push the history of fty-log plus this PR to the new repository

**Comment by MimiXav** [comment]
I take the name fty-log because, it's was short and succinct !!

**Comment by bstepankova** [comment]
for me fty-log is perfect too

**Comment by michal42** [comment]
:+1:

**Comment by EldoreiJK** [comment]
It sounds good to me as well, but I quite agree with Arnaud it will be a mess to distinguish agents from libraries if we'd have fty-log, fty-db, fty-rest (again)... You know, devil's advocate.

**Comment by jana-rapava** [comment]
Closing because this change was moved fty-common-logging repo.

**Pull request closed without merging**
